### ISSUE TITLE
Можно заменить на when

### ISSUE THREAD

**Issue by kozlyakov-m** [xWillQ/Task_1#1]
https://github.com/xWillQ/Task_1/blob/5a17fba295e7fe319e4dc45411b07ddbe24066d2/lvl_6.kt#L18

**Comment by xWillQ** [comment]
Как? Не вижу способа сделать такое сравнение с помощью when.

**Comment by kozlyakov-m** [comment]
> Как? Не вижу способа сделать такое сравнение с помощью when.

Тупанул, неможно)

**Comment by xWillQ** [comment]
Оказывается можно!
https://github.com/xWillQ/Task_1/blob/5f2bf6cac09b4f7fd560306fdb3f901d98ef1e31/lvl_6.kt#L17-L36
