### ISSUE TITLE
??

### ISSUE THREAD

**Issue by AndreiSerov** [xWillQ/Task_1#3]
Maybe rename vasya to vasya? 
https://github.com/xWillQ/Task_1/blob/52cf78e3ede12048a3cf3a807a7808501ccf1cde/lvl_8.kt#L16

**Comment by xWillQ** [comment]
Что?

**Comment by AndreiSerov** [comment]
`var args = args`

**Comment by PetrSed** [comment]
Unnecessary action he has in mind

**Comment by xWillQ** [comment]
Это было сделано для изменения свойств переменной. Все аргументы являются val, то есть их нельзя изменять, а мне нужно было добавить туда новые значения, так что пришлось переобъявить переменную с помощью var.

**Comment by AndreiSerov** [comment]
Ну нам сегодня уже говорили, что переменных должно быть как можно меньше. И в данном случае, таких штук вроде аргс = аргс, думаю, что точно быть не должно

**Comment by ABashkirova** [comment]
Используйте args, если это действительно входные параметры. 
Не используйте переменную с таким же названием для другого, то есть для stdin 
_Почему?_
Это влияет на читаемость кода, путает ревьювера. Может и спутать и вас, как только забудете зачем так писали.
_И чо?_
CodeStyle, культура программирования и чистый код — это важно, потому что это часть качественных коммуникаций в команде.

**Comment by xWillQ** [comment]
Спасибо за подробное объяснение, я понимаю что такое Code style. Проблему исправил.
