### ISSUE TITLE
Задание3: Используйте более подходящую структуру данных

### ISSUE THREAD

**Issue by ABashkirova** [xWillQ/Task_1#5]
Проблема вот в этой строке: 
https://github.com/xWillQ/Task_1/blob/b9ce91927cd4dd3ca1365360e73c64dabce5abec/lvl_3.kt#L4
Приходится заполнить мэп нулями, чтобы получить результат. Чтобы получить уникальные значения, попробуйте структуру множества: Set
https://github.com/xWillQ/Task_1/blob/b9ce91927cd4dd3ca1365360e73c64dabce5abec/lvl_3.kt#L2

**Comment by xWillQ** [comment]
Исправил.
